### ISSUE TITLE
SQL ServerからPostgreSQLへ移行

### ISSUE THREAD

**Issue by akiyamashino** [Implem/Implem.Pleasanter#375]
公式マニュアルの
　・プリザンター(.NET Core/PostgreSQL)をUbuntuにインストールする
　・プリザンターのDBをSQL ServerからPostgreSQLへ移行する手順
を見ながら手順を追っています。

　●親(Windows10Pro)にSQL server expressとプリザンターをインストール。 
　　http://192.168.10.14:1759/pleasanter/で入れる状態。
　　BinaryStorage.json
    "Provider": "Local",
    "Path": "c:\\pripic",
    で使用しています。
　●Hyper-Vにubuntu20.04 serverをインストール
　　192.168.10.33

以下に部分部分ピックアップして記載します。

※　以下は該当箇所なかったので変更していません。（すでになっている？）
　　PostgreSQLの認証方式の設定
　　/etc/postgresql/12/main/pg_hba.confを開き、METHODの"ident"を"md5"に変更します

webのフォルダを作成。(777)
してプリザンターのPleasanter.NetCore_1.1.36.0.zipを解凍。

/web/pleasanter/Implem.Pleasanter/App_Data/Parameters/Migration.json
のファイルにパスワードを入れて"(local)"を192.168.10.14と記入。

以下のコマンドを入れると
dotnet Implem.CodeDefiner.NetCore.dll migrate

以下のメッセージが表示が出てしまいます。
<INFO> UsersConfigurator.Execute: Implem.Pleasanter_Owner
<INFO> UsersConfigurator.Execute: Implem.Pleasanter_User
<INFO> TablesConfigurator.ConfigureTableSet: Tenants
<INFO> TablesConfigurator.ConfigureTableSet: Demos
<INFO> TablesConfigurator.ConfigureTableSet: Extensions
<INFO> TablesConfigurator.ConfigureTableSet: Sessions
<INFO> TablesConfigurator.ConfigureTableSet: SysLogs
<INFO> TablesConfigurator.ConfigureTableSet: Statuses
<INFO> TablesConfigurator.ConfigureTableSet: ReminderSchedules
<INFO> TablesConfigurator.ConfigureTableSet: Depts
<INFO> TablesConfigurator.ConfigureTableSet: Groups
<INFO> TablesConfigurator.ConfigureTableSet: GroupMembers
<INFO> TablesConfigurator.ConfigureTableSet: Registrations
<INFO> TablesConfigurator.ConfigureTableSet: Users
<INFO> TablesConfigurator.ConfigureTableSet: LoginKeys
<INFO> TablesConfigurator.ConfigureTableSet: MailAddresses
<INFO> TablesConfigurator.ConfigureTableSet: OutgoingMails
<INFO> TablesConfigurator.ConfigureTableSet: Items
<INFO> TablesConfigurator.ConfigureTableSet: Sites
<INFO> TablesConfigurator.ConfigureTableSet: Orders
<INFO> TablesConfigurator.ConfigureTableSet: ExportSettings
<INFO> TablesConfigurator.ConfigureTableSet: Links
<INFO> TablesConfigurator.ConfigureTableSet: Binaries
<INFO> TablesConfigurator.ConfigureTableSet: Permissions
<INFO> TablesConfigurator.ConfigureTableSet: Issues
<INFO> TablesConfigurator.ConfigureTableSet: Results
<INFO> TablesConfigurator.ConfigureTableSet: Wikis
<INFO> TablesConfigurator.ConfigureFullTextIndex:
<INFO> PrivilegeConfigurator.Execute: Implem.Pleasanter_Owner
<INFO> PrivilegeConfigurator.Execute: Implem.Pleasanter_User
<SUCCESS> Starter.ConfigureDatabase: Database configuration has been completed.
Unhandled exception. System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Implem.CodeDefiner.Functions.AspNetMvc.CSharp.Migrator.MigrateTable(String tableName, String identity) in C:\Implem\Pleasanter.NetCore\Implem.CodeDefiner\Functions\AspNetMvc\CSharp\Migrator.cs:line 40
   at Implem.CodeDefiner.Functions.AspNetMvc.CSharp.Migrator.<>c.<MigrateDatabaseAsync>b__0_6(String tableName) in C:\Implem\Pleasanter.NetCore\Implem.CodeDefiner\Functions\AspNetMvc\CSharp\Migrator.cs:line 25
   at Implem.Libraries.Utilities.Linqs.ForEach[T](IEnumerable`1 source, Action`1 action) in C:\Implem\Pleasanter.NetCore\Implem.Libraries\Utilities\Linqs.cs:line 11
   at Implem.CodeDefiner.Functions.AspNetMvc.CSharp.Migrator.MigrateDatabaseAsync() in C:\Implem\Pleasanter.NetCore\Implem.CodeDefiner\Functions\AspNetMvc\CSharp\Migrator.cs:line 31
   at Implem.CodeDefiner.Starter.MigrateDatabase() in C:\Implem\Pleasanter.NetCore\Implem.CodeDefiner\Starter.cs:line 172
   at Implem.CodeDefiner.Starter.Main(String[] args) in C:\Implem\Pleasanter.NetCore\Implem.CodeDefiner\Starter.cs:line 78
   at Implem.CodeDefiner.NetCore.Program.Main(String[] args) in C:\Implem\Pleasanter.NetCore\Implem.CodeDefiner.NetCore\Program.cs:line 11
ClientConnectionId:00000000-0000-0000-0000-000000000000
中止 (コアダンプ)

プリザンターは初期状態で起動できます。

以上、大変すみませんがどなたかアドバイスをお願いいたします。

**Comment by akiyamashino** [comment]
検索していろいろなサイトを見ておりました
SQL Server Browserが停止状態でした。何か関係あるでしょうか？
expressのせいか起動できません。

**Comment by akiyamashino** [comment]
すません。自己解決しました。
expressでもSQL Server Browser開始をすれば出来ました。
(グレー表示で変更できないと思い込んでいました)
