### ISSUE TITLE
新規作成時にエラーが発生する

### ISSUE THREAD

**Issue by kazuca** [Implem/Implem.Pleasanter#378]
1.2.2.0で新規作成→作成を行うと、下記のようなエラーが発生します。作成自体は行われているのですが、画面の書き換えが正常に行われず、「アプリケーションエラー」のメッセージが出力されます。

```
Object reference not set to an instance of an object.
   at Implem.ParameterAccessor.Parts.ExtendedSql.ReplacedCommandText(Int64 siteId, Int64 id, Nullable`1 timestamp, Dictionary`2 columnPlaceholders) in C:\Implem\Pleasanter.NetCore\Implem.ParameterAccessor\Parts\ExtendedSql.cs:line 39
   at Implem.Pleasanter.Libraries.DataSources.Rds.<>c__DisplayClass75_0.<ExtendedSqls>b__0(ExtendedSql o) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Libraries\DataSources\Rds.cs:line 4226
   at Implem.Libraries.Utilities.Linqs.ForEach[T](IEnumerable`1 source, Action`1 action) in C:\Implem\Pleasanter.NetCore\Implem.Libraries\Utilities\Linqs.cs:line 13
   at Implem.Pleasanter.Libraries.DataSources.Rds.OnCreatedExtendedSqls(List`1 statements, Context context, Int64 siteId, Int64 id) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Libraries\DataSources\Rds.cs:line 3943
   at Implem.Pleasanter.Models.ResultModel.Create(Context context, SiteSettings ss, TableTypes tableType, SqlParamCollection param, Boolean extendedSqls, Boolean synchronizeSummary, Boolean forceSynchronizeSourceSummary, Boolean notice, Boolean otherInitValue, Boolean get) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Models\Results\ResultModel.cs:line 1040
   at Implem.Pleasanter.Models.ResultUtilities.Create(Context context, SiteSettings ss) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Models\Results\ResultUtilities.cs:line 2622
   at Implem.Pleasanter.Models.ItemModel.Create(Context context) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Models\Items\ItemModel.cs:line 1868
   at Implem.Pleasanter.Controllers.ItemsController.Create(Context context, Int64 id) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Controllers\ItemsController.cs:line 443
   at Implem.Pleasanter.NetCore.Controllers.ItemsController.Create(Int64 id) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter.NetCore\Controllers\ItemsController.cs:line 490
   at lambda_method2461(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

**Comment by kazuca** [comment]
1.2.3.0で解消されていることが確認できましたので、クローズします。
