### ISSUE TITLE
.NET Core 1.2.6.0 x Windows Serverx x SQL Server：フィルタで「自分」を選択時に、フィルタされた項目の編集画面に遷移できない

### ISSUE THREAD

**Issue by tatsuyasenbom** [Implem/Implem.Pleasanter#384]
# 環境(`NG`:下記`現象`が発生した環境、`OK`:発生しなかった環境)
* `OK`:`Windows Server 2016` x `SQL Server 2016` x `Pleasanter .NET Framework 版 0.50.100.21642`
* `OK`:`Ubuntu 20.04LTS` x `PostgreSQL` x `Pleasanter .NET Core 版 1.2.6.0`
* `NG`:`Windows Server 2016` x `SQL Server 2016` x `Pleasanter .NET Core 版 1.2.6.0`
    * 上記`Windows Server 2016` x `SQL Server 2016` x `Pleasanter .NET Framework 版 0.50.100.21642`からのアップデート
* `NG`:`Windows Server 2019` x `SQL Server 2019` x `Pleasanter .NET Core 版 1.2.6.0`
    * アップデートなく一から整備

-----------------------

# 現象
* 症状は過去に報告・修正されている[フィルタで「自分」を選択時に、フィルタされた項目の編集画面に遷移できない #342](https://github.com/Implem/Implem.Pleasanter/issues/342)と類似
* 手順
    1. `トップ`>`+ 新規作成`>`期限付きテーブル`を作成
    2. 上記2で作成した`期限付きテーブル`上で`+ 新規作成`でレコードを作成
    3. 上記2で作成した`期限付きテーブル`の`一覧`で`フィルタ`>`自分`にチェックを入れる
    4. 上記4の後に表示された`一覧`のレコードのリンクをクリック
    5. フッターに`アプリケーションで問題が発生しました。`を確認

-----------------------

# SysLogs
* 上記`現象`>`移行環境`でエラーが発生した際のログ
* `ErrMessage`
    * `変数名 '@_U' は既に宣言されています。変数名は、クエリ バッチまたはストアド プロシージャ内で一意にしてください。`
* `ErrStackTrace`

```
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SqlClient.SqlCommand.ExecuteReader()
   at Implem.Libraries.DataSources.SqlServer.SqlIo.<>c__DisplayClass15_0.<ExecuteScalar>b__0() in C:\Implem\Pleasanter.NetCore\Implem.Libraries\DataSources\SqlServer\SqlIo.cs:line 150
   at Implem.Libraries.DataSources.SqlServer.SqlIo.Try(ISqlObjectFactory factory, Action action) in C:\Implem\Pleasanter.NetCore\Implem.Libraries\DataSources\SqlServer\SqlIo.cs:line 295
   at Implem.Libraries.DataSources.SqlServer.SqlIo.ExecuteScalar(ISqlObjectFactory factory, IDbTransaction dbTransaction, IDbConnection dbConnection) in C:\Implem\Pleasanter.NetCore\Implem.Libraries\DataSources\SqlServer\SqlIo.cs:line 163
   at Implem.Libraries.DataSources.SqlServer.SqlIo.ExecuteScalar_int(ISqlObjectFactory factory, IDbTransaction dbTransaction, IDbConnection dbConnection) in C:\Implem\Pleasanter.NetCore\Implem.Libraries\DataSources\SqlServer\SqlIo.cs:line 354
   at Implem.Pleasanter.Libraries.DataSources.Rds.ExecuteScalar_int(Context context, IDbTransaction dbTransaction, IDbConnection dbConnection, String connectionString, Boolean transactional, Boolean writeSqlToDebugLog, SqlStatement[] statements) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Libraries\DataSources\Rds.cs:line 84
   at Implem.Pleasanter.Libraries.DataSources.Repository.<>c__DisplayClass3_0.<ExecuteScalar_int>b__0(IDbTransaction transaction, IDbConnection connection) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Libraries\DataSources\Repository.cs:line 171
   at Implem.Pleasanter.Libraries.DataSources.Rds.ExecuteScalar[T](Context context, String connectionString, Boolean transactional, Func`3 func) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Libraries\DataSources\Rds.cs:line 238
   at Implem.Pleasanter.Libraries.DataSources.Repository.ExecuteScalar_int(Context context, Boolean transactional, SqlStatement[] statements) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Libraries\DataSources\Repository.cs:line 166
   at Implem.Pleasanter.Models.IssueUtilities.GetSwitchTargets(Context context, SiteSettings ss, Int64 issueId, Int64 siteId) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Models\Issues\IssueUtilities.cs:line 2332
   at Implem.Pleasanter.Models.IssueUtilities.Editor(Context context, SiteSettings ss, Int64 issueId, Boolean clearSessions) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Models\Issues\IssueUtilities.cs:line 1326
   at Implem.Pleasanter.Models.ItemModel.Editor(Context context) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Models\Items\ItemModel.cs:line 964
   at Implem.Pleasanter.Controllers.ItemsController.Edit(Context context, Int64 id) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Controllers\ItemsController.cs:line 220
   at Implem.Pleasanter.NetCore.Controllers.ItemsController.Edit(Int64 id) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter.NetCore\Controllers\ItemsController.cs:line 230
   at lambda_method740(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

* その他

| CreatedTime | SysLogId | Ver | SysLogType | OnAzure | MachineName | ServiceName | TenantName | Application | Class | Method | RequestData | HttpMethod | RequestSize | ResponseSize | Elapsed | ApplicationAge | ApplicationRequestInterval | SessionAge | SessionRequestInterval | WorkingSet64 | VirtualMemorySize64 | ProcessId | ProcessName | BasePriority | Url | UrlReferer | UserHostName | UserHostAddress | UserLanguage | UserAgent | SessionGuid | InDebug | AssemblyVersion | Comments | Creator | Updator | UpdatedTime |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 2021-09-13 14:39:46.613 | 3629447 | 1 | 10 | NULL | WIN-1H8MFFKK2HK:Microsoft Windows NT 10.0.14393.0 | Implem.Pleasanter | NULL | Implem.DefinitionAccessor | items | edit | NULL | GET | NULL | NULL | NULL | 22259.1199 | 48.7615 | -0.0005 | 625.7922 | NULL | NULL | NULL | NULL | NULL | https://pleasanter.test.com/pleasanter/items/1426982/edit | https://pleasanter.test.com/pleasanter/items/1426981/index | 192.168.14.99 | 192.168.14.99 | ja | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36 | EEB85D9F695140B3829756CD8E4037FA   | NULL | 1.2.6.0 | NULL | 118 | 118 | 2021-09-13 14:39:46.613 |

**Comment by tatsuyasenbom** [comment]
早急に、ご対応いただきありがとうございました。

`1.2.7.0`へアップデートしたところ、報告させていただいた現象が、以下が環境で発生しないことを確認しました。

* `Windows Server 2016 x SQL Server 2016 x Pleasanter .NET Core 版 1.2.7.0`
* `Windows Server 2019 x SQL Server 2019 x Pleasanter .NET Core 版 1.2.7.0`
* `Ubuntu 20.04LTS x PostgreSQL x Pleasanter .NET Core 版 1.2.7.0`

よって、これにて本件はクローズさせていただきます。

![image](https://user-images.githubusercontent.com/87968771/133924439-5c4c01f0-ee34-4836-b1df-9475e83f8c64.png)

**Comment by uchi-ta** [comment]
ご不便おかけしました。ご確認いただきありがとうございます。
