### ISSUE TITLE
特定の日付入力を行い登録すると「アプリケーションで問題が発生しました」となり登録できない

### ISSUE THREAD

**Issue by h595a** [Implem/Implem.Pleasanter#458]
下記の日付を入力し登録すると、「アプリケーションで問題が発生しました」が発生します。

発生する条件として下記の3条件が重なった場合です。

1. ユーザーのタイムゾーンがブランクではない場合

（ユーザーを新規登録する時にタイムゾーンは「日本標準時」となり、この状態です）

![image](https://user-images.githubusercontent.com/128195455/226072286-05ea0f56-1321-47d7-abf1-916a72f7f45b.png)

2. 発生する日付は、下記の通り日本のサマータイム開始日

- 1948/5/2
- 1949/4/3
- 1950/5/7
- 1951/5/6

3. 日付項目のエディタの書式「年月日」の状態
![image](https://user-images.githubusercontent.com/128195455/226072390-a846ca15-f3b1-4ef3-81b9-9562242d133b.png)

上記３条件ですと発生します。

なお、こちらで確認した状況において、
エディタの書式を「日付と時刻（分）」、時刻間隔（分）を「１」に設定すると、
日付項目に入力した値が、自動的に強制的に1時間加算される状態となり、この状態ですと問題なく登録できます。

![image](https://user-images.githubusercontent.com/128195455/226072405-4d1336e7-063c-4830-934e-9ba4d52f4dc1.png)

例）　1948/05/02 と入力して項目からフォーカスが外れると、1948/05/02 01:00　となります。
![image](https://user-images.githubusercontent.com/128195455/226072330-b6ea5422-f2b6-4f6b-9805-21646df03702.png)
↓
![image](https://user-images.githubusercontent.com/128195455/226072337-367657e8-cc9e-44f2-8af7-7be2823ccf47.png)

日本のサマータイム開始日以外ですと、00:00 が入力できる状況です。
![image](https://user-images.githubusercontent.com/128195455/226072353-47fee170-1950-4ec5-938e-931c77d74246.png)

当方の環境は、Linux環境で、Pleasanterのバージョンはバージョン1.3.29.2です。

エラー発生時のエラーログを下記に添付します。

要求データ
`Issues_DateA=1948%2f05%2f02&ControlId=UpdateCommand&VerUp=true&ControlledOrder=&Issues_Timestamp=2023%2f3%2f17+4%3a44%3a20.011&IsNew=0`

Httpメソッド
`PUT`

Url
`http://pleasanter/items/130712/update`

リファラ
`http://pleasanter/items/130712`

ユーザエージェント
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36`

エラーメッセージ
`ArgumentException: The supplied DateTime represents an invalid time. For example, when the clock is adjusted forward, any time in the period that is skipped is invalid. (Parameter 'dateTime')`

エラースタックトレース
```
   at System.TimeZoneInfo.ConvertTime(DateTime dateTime, TimeZoneInfo sourceTimeZone, TimeZoneInfo destinationTimeZone, TimeZoneInfoOptions flags, CachedData cachedData)
   at Implem.Pleasanter.Libraries.Server.Times.ToUniversal(DateTime value, Context context) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Libraries\Server\Times.cs:line 56
   at Implem.Pleasanter.Models.IssueModel.<>c__DisplayClass72_0.<SetByForm>b__0(KeyValuePair`2 data) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Models\Issues\IssueModel.cs:line 2660
   at Implem.Libraries.Utilities.Linqs.ForEachT in C:\Implem\Pleasanter.NetCore\Implem.Libraries\Utilities\Linqs.cs:line 13
   at Implem.Pleasanter.Models.IssueModel.SetByForm(Context context, SiteSettings ss, Dictionary`2 formData) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Models\Issues\IssueModel.cs:line 2605
   at Implem.Pleasanter.Models.IssueModel..ctor(Context context, SiteSettings ss, Int64 issueId, View view, Dictionary`2 formData, Boolean setByApi, Boolean clearSessions, List`1 switchTargets, MethodTypes methodType) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Models\Issues\IssueModel.cs:line 730
   at Implem.Pleasanter.Models.IssueUtilities.Update(Context context, SiteSettings ss, Int64 issueId, String previousTitle) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Models\Issues\IssueUtilities.cs:line 3294
   at Implem.Pleasanter.Models.ItemModel.Update(Context context) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Models\Items\ItemModel.cs:line 1542
   at Implem.Pleasanter.Controllers.ItemsController.Update(Int64 id) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Controllers\ItemsController.cs:line 635
   at lambda_method1445(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

**Comment by uchi-ta** [comment]
貢献ありがとうございます。調査いたします。

**Comment by h595a** [comment]
未解決

**Comment by h595a** [comment]
解決していない issue なので reopen お願いできますでしょうか。
調査および対応できないほどの困難な issue であれば、機械的なクローズに任せるのでなく、
コメントいただけたら幸いです。

**Comment by pierre3** [comment]
再オープンいたしました。

Issueありがとうございます。
対応が進まず申し訳ございません。確認いたしますので今しばらくお待ちください。

**Comment by nagamune-implem** [comment]
本件ですが、Pleasanter_1.3.45.0リリース版で対応いたしました。
対応内容としましては、「アプリケーションで問題が発生しました」となる場合の例外処理対応を記載し、該当レコードの登録・更新ができるようにいたしました。
