### ISSUE TITLE
SysLogsに出力されるスタックトレースについて

### ISSUE THREAD

**Issue by yohshiro-711** [Implem/Implem.Pleasanter#570]
サーバースクリプトでエラーが発生した際に出力されるスタックトレースの内容について
エラーの原因が特定できない内容が出力されているためClearScriptの詳細なエラー情報を出力できないでしょうか。

https://github.com/Implem/Implem.Pleasanter/blob/62816199ae7de58e812fb46210de18487f870de6/Implem.Pleasanter/Filters/HandleErrorExAttribute.cs#L27

HandleErrorExAttributeクラスでStackTraceに設定している値を `filterContext.Exception.StackTrace` から
`filterContext.Exception.ToString()` に変更するだけでもサーバースクリプトのエラー原因特定に有用な情報が出力されるため検討していただきたいです。

現在、本番環境のサーバースクリプトで発生したエラーの原因特定ができない場合は
一時的にソースを `filterContext.Exception.ToString()` に変更してビルドして配置しエラーの詳細内容を確認しています。
※API実行のときだけエラーが起きる場合等、context.Logが使えないためとても困ってます。

**Comment by yohshiro-711** [comment]
以下、製品標準のスタックトレースと `filterContext.Exception.ToString()` に変更したときの違いです。

### 製品標準
```
エラーメッセージ：ScriptEngineException: Error: Object reference not set to an instance of an object.
スタックトレース：
at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative.ThrowScheduledException()
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative.Invoke(Action`1 action)
   at Microsoft.ClearScript.V8.SplitProxy.V8ContextProxyImpl.InvokeWithLock(Action action)
   at Microsoft.ClearScript.V8.V8ScriptEngine.ScriptInvoke[T](http://127.0.0.1/syslogs/Func%601%20func)
   at Microsoft.ClearScript.V8.V8ScriptEngine.Execute(UniqueDocumentInfo documentInfo, String code, Boolean evaluate)
   at Microsoft.ClearScript.ScriptEngine.Execute(DocumentInfo documentInfo, String code)
   at Implem.Pleasanter.Libraries.ServerScripts.ScriptEngine.Execute(String code, Boolean debug) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Libraries\ServerScripts\ScriptEngine.cs:line 48
   at Implem.Pleasanter.Libraries.ServerScripts.ServerScriptUtilities.Execute(Context context, SiteSettings ss, GridData gridData, BaseItemModel itemModel, View view, ServerScript[] scripts, String condition, Boolean debug, Boolean onTesting) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Libraries\ServerScripts\ServerScriptUtilities.cs:line 1123
   at Implem.Pleasanter.Libraries.ServerScripts.ServerScriptUtilities.Execute(Context context, SiteSettings ss, GridData gridData, BaseItemModel itemModel, View view, Func`2 where, String condition) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Libraries\ServerScripts\ServerScriptUtilities.cs:line 1187
   at Implem.Pleasanter.Models.BaseItemModel.SetByBeforeCreateServerScript(Context context, SiteSettings ss) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Models\Shared\_BaseModel.cs:line 998
   at Implem.Pleasanter.Models.ResultModel.Create(Context context, SiteSettings ss, TableTypes tableType, SqlParamCollection param, List`1 processes, Int64 copyFrom, Boolean extendedSqls, Boolean synchronizeSummary, Boolean forceSynchronizeSourceSummary, Boolean notice, String noticeType, Boolean otherInitValue, Boolean get) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Models\Results\ResultModel.cs:line 1390
   at Implem.Pleasanter.Models.ResultUtilities.Create(Context context, SiteSettings ss) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Models\Results\ResultUtilities.cs:line 3074
   at Implem.Pleasanter.Models.ItemModel.Create(Context context) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Models\Items\ItemModel.cs:line 1720
   at Implem.Pleasanter.Controllers.ItemsController.Create(Int64 id) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Controllers\ItemsController.cs:line 632
   at lambda_method1086(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

### `filterContext.Exception.ToString()`  に変更した場合
```
Microsoft.ClearScript.ScriptEngineException: Error: Object reference not set to an instance of an object.
 ---> Microsoft.ClearScript.ScriptEngineException: Error: Object reference not set to an instance of an object.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Implem.Pleasanter.Models.ExtensionUtilities.DataSetToExpando(DataSet dataSet) in C:\work\Implem.Pleasanter-Pleasanter_1.4.5.0\Implem.Pleasanter\Models\Extensions\ExtensionUtilities.cs:line 161
   at Implem.Pleasanter.Models.ExtensionUtilities.ExecuteDataSetAsDynamic(Context context, String name, Dictionary`2 _params) in C:\work\Implem.Pleasanter-Pleasanter_1.4.5.0\Implem.Pleasanter\Models\Extensions\ExtensionUtilities.cs:line 83
   at Implem.Pleasanter.Libraries.ServerScripts.ServerScriptModelExtendedSql.ExecuteDataSet(String name, Object _params) in C:\work\Implem.Pleasanter-Pleasanter_1.4.5.0\Implem.Pleasanter\Libraries\ServerScripts\ServerScriptModelExtendedSql.cs:line 21
   at Implem.Pleasanter.Libraries.ServerScripts.ServerScriptModelExtendedSql.ExecuteTable(String name, Object _params) in C:\work\Implem.Pleasanter-Pleasanter_1.4.5.0\Implem.Pleasanter\Libraries\ServerScripts\ServerScriptModelExtendedSql.cs:line 30
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.ClearScript.Util.InvokeHelpers.<>c.<InvokeMethod>b__0_0(MethodInfo invokeMethod, Object invokeTarget, Object[] invokeArgs)
   at Microsoft.ClearScript.Util.InvokeHelpers.InvokeMethodInternal[T](http://127.0.0.1/syslogs/IHostContext%20context,%20T%20method,%20Object%20target,%20Object[]%20args,%20Func%604%20invoker,%20Type%20returnType,%20ScriptMemberFlags%20flags)
   at Microsoft.ClearScript.Util.InvokeHelpers.InvokeMethod(IHostContext context, MethodInfo method, Object target, Object[] args, ScriptMemberFlags flags)
   at Microsoft.ClearScript.HostItem.MethodBindSuccess.Invoke(HostItem hostItem)
   at Microsoft.ClearScript.HostItem.InvokeMethod(String name, Type[] typeArgs, Object[] args, Object[] bindArgs)
   at Microsoft.ClearScript.HostItem.InvokeMethod(String name, Object[] args, Object[] bindArgs)
   at Microsoft.ClearScript.HostItem.InvokeHostMember(String name, BindingFlags invokeFlags, Object[] args, Object[] bindArgs, Boolean& isCacheable)
   at Microsoft.ClearScript.HostItem.InvokeMember(String name, BindingFlags invokeFlags, Object[] args, Object[] bindArgs, CultureInfo culture, Boolean bypassTunneling, Boolean& isCacheable)
   at Microsoft.ClearScript.HostItem.InvokeMember(String name, BindingFlags invokeFlags, Object[] args, Object[] bindArgs, CultureInfo culture, Boolean bypassTunneling)
   at Microsoft.ClearScript.HostMethod.TryInvoke(IHostContext context, BindingFlags invokeFlags, Object[] args, Object[] bindArgs, Object& result)
   at Microsoft.ClearScript.Util.InvokeHelpers.TryInvokeObject(IHostContext context, Object target, BindingFlags invokeFlags, Object[] args, Object[] bindArgs, Boolean tryDynamic, Object& result)
   at Microsoft.ClearScript.HostItem.InvokeHostMember(String name, BindingFlags invokeFlags, Object[] args, Object[] bindArgs, Boolean& isCacheable)
   at Microsoft.ClearScript.HostItem.InvokeMember(String name, BindingFlags invokeFlags, Object[] args, Object[] bindArgs, CultureInfo culture, Boolean bypassTunneling, Boolean& isCacheable)
   at Microsoft.ClearScript.HostItem.<>c__DisplayClass151_0.<InvokeReflectMember>b__0()
   at Microsoft.ClearScript.ScriptEngine.HostInvoke[T](http://127.0.0.1/syslogs/Func%601%20func)
   at Microsoft.ClearScript.HostItem.HostInvoke[T](http://127.0.0.1/syslogs/Func%601%20func)
   at Microsoft.ClearScript.HostItem.InvokeReflectMember(String name, BindingFlags invokeFlags, Object[] wrappedArgs, CultureInfo culture, String[] namedParams, Boolean& isCacheable)
   at Microsoft.ClearScript.HostItem.InvokeReflectMember(String name, BindingFlags invokeFlags, Object[] wrappedArgs, CultureInfo culture, String[] namedParams)
   at Microsoft.ClearScript.HostItem.System.Reflection.IReflect.InvokeMember(String name, BindingFlags invokeFlags, Binder binder, Object invokeTarget, Object[] wrappedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at Microsoft.ClearScript.HostItem.Microsoft.ClearScript.Util.IDynamic.Invoke(Boolean asConstructor, Object[] args)
   at Microsoft.ClearScript.V8.V8ProxyHelpers.InvokeHostObject(Object obj, Boolean asConstructor, Object[] args)
   at Microsoft.ClearScript.V8.V8ProxyHelpers.InvokeHostObject(IntPtr pObject, Boolean asConstructor, Object[] args)
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyManaged.InvokeHostObject(IntPtr pObject, Boolean asConstructor, Int32 argCount, Ptr pArgs, Ptr pResult)
   --- End of inner exception stack trace ---
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative.ThrowScheduledException()
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative.Invoke[T](http://127.0.0.1/syslogs/Func%602%20func)
   at Microsoft.ClearScript.V8.SplitProxy.V8ContextProxyImpl.Execute(UniqueDocumentInfo documentInfo, String code, Boolean evaluate)
   at Microsoft.ClearScript.V8.V8ScriptEngine.ExecuteRaw(UniqueDocumentInfo documentInfo, String code, Boolean evaluate)
   at Microsoft.ClearScript.V8.V8ScriptEngine.ExecuteInternal(UniqueDocumentInfo documentInfo, String code, Boolean evaluate)
   at Microsoft.ClearScript.V8.V8ScriptEngine.<>c__DisplayClass130_0.<Execute>b__0()
   at Microsoft.ClearScript.ScriptEngine.ScriptInvokeInternal[T](http://127.0.0.1/syslogs/Func%601%20func)
   at Microsoft.ClearScript.V8.V8ScriptEngine.<>c__DisplayClass137_0`1.<ScriptInvoke>b__0()
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyManaged.InvokeHostAction(IntPtr pAction)
   --- Script error details follow ---
   Error: Object reference not set to an instance of an object.
       at Script [2]:2:26 -> let result = extendedSql.ExecuteTable('TestSql');
   --- End of inner exception stack trace ---
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative.ThrowScheduledException()
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative.Invoke(Action`1 action)
   at Microsoft.ClearScript.V8.SplitProxy.V8ContextProxyImpl.InvokeWithLock(Action action)
   at Microsoft.ClearScript.V8.V8ScriptEngine.ScriptInvoke[T](http://127.0.0.1/syslogs/Func%601%20func)
   at Microsoft.ClearScript.V8.V8ScriptEngine.Execute(UniqueDocumentInfo documentInfo, String code, Boolean evaluate)
   at Microsoft.ClearScript.ScriptEngine.Execute(DocumentInfo documentInfo, String code)
   at Implem.Pleasanter.Libraries.ServerScripts.ScriptEngine.Execute(String code, Boolean debug) in C:\work\Implem.Pleasanter-Pleasanter_1.4.5.0\Implem.Pleasanter\Libraries\ServerScripts\ScriptEngine.cs:line 48
   at Implem.Pleasanter.Libraries.ServerScripts.ServerScriptUtilities.Execute(Context context, SiteSettings ss, GridData gridData, BaseItemModel itemModel, View view, ServerScript[] scripts, String condition, Boolean debug, Boolean onTesting) in C:\work\Implem.Pleasanter-Pleasanter_1.4.5.0\Implem.Pleasanter\Libraries\ServerScripts\ServerScriptUtilities.cs:line 1120
   at Implem.Pleasanter.Libraries.ServerScripts.ServerScriptUtilities.Execute(Context context, SiteSettings ss, GridData gridData, BaseItemModel itemModel, View view, Func`2 where, String condition) in C:\work\Implem.Pleasanter-Pleasanter_1.4.5.0\Implem.Pleasanter\Libraries\ServerScripts\ServerScriptUtilities.cs:line 1181
   at Implem.Pleasanter.Models.BaseItemModel.SetByBeforeCreateServerScript(Context context, SiteSettings ss) in C:\work\Implem.Pleasanter-Pleasanter_1.4.5.0\Implem.Pleasanter\Models\Shared\_BaseModel.cs:line 997
   at Implem.Pleasanter.Models.ResultModel.Create(Context context, SiteSettings ss, TableTypes tableType, SqlParamCollection param, List`1 processes, Int64 copyFrom, Boolean extendedSqls, Boolean synchronizeSummary, Boolean forceSynchronizeSourceSummary, Boolean notice, String noticeType, Boolean otherInitValue, Boolean get) in C:\work\Implem.Pleasanter-Pleasanter_1.4.5.0\Implem.Pleasanter\Models\Results\ResultModel.cs:line 1390
   at Implem.Pleasanter.Models.ResultUtilities.Create(Context context, SiteSettings ss) in C:\work\Implem.Pleasanter-Pleasanter_1.4.5.0\Implem.Pleasanter\Models\Results\ResultUtilities.cs:line 3073
   at Implem.Pleasanter.Models.ItemModel.Create(Context context) in C:\work\Implem.Pleasanter-Pleasanter_1.4.5.0\Implem.Pleasanter\Models\Items\ItemModel.cs:line 1720
   at Implem.Pleasanter.Controllers.ItemsController.Create(Int64 id) in C:\work\Implem.Pleasanter-Pleasanter_1.4.5.0\Implem.Pleasanter\Controllers\ItemsController.cs:line 632
   at lambda_method1123(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   --- Script error details follow ---
   Error: Object reference not set to an instance of an object.
       at Script [2]:2:26 -> let result = extendedSql.ExecuteTable('TestSql');
```

**Comment by nagamune-implem** [comment]
Issueありがとうございます。

また有用なご提案を頂き感謝いたします。
内容を確認いたしますので、しばらくお待ち頂きたくよろしくお願いいたします。

**Comment by nagamune-implem** [comment]
@yohshiro-711 
本件に関しまして、Syslogsテーブルへの出力で無いといけない条件がございますでしょうか？
サーバスクリプトのコード内のtry/catchの例外をブラウザのコンソールに出力する事によって、サーバスクリプトコードエラーの補足情報が出力されます。

●参考
FAQ：サーバスクリプトのエラーログを出力したい | Pleasanter
https://pleasanter.org/ja/manual/faq-server-script-log

---
以降、動作例

### ブラウザのコンソール出力
```
処理開始
エラー発生
ReferenceError: myItem is not defined
    at Script [2]:4:17
```
※）「myItem が無い」と出力している。
	

### サーバスクリプトに下記を登録（トリガー：レコード更新時）
```js
try {
    context.Log('処理開始');
    context.Log(myItem.Title);
    context.Log('処理終了');
} catch(e) {
    context.Log('エラー発生');
    // エラーログ出力
    context.Log(e.stack);    
}
```

**Comment by yohshiro-711** [comment]
@nagamune-implem

ご回答ありがとうございます。
ブラウザ実行でのエラーならその方法でも確認できることは認識しています。
最初の投稿でも記載しましたが、APIで実行したときだけエラーになることがあり、
その場合に原因特定が難しいということです。

また、出来ればブラウザ実行であってもcontext.Logでのログ出力は可能であれば行いたくないと考えています。
お客様に開発者ツールを開いてそこのエラー内容を送付して頂くことになることと
すべてのサーバースクリプトにcontext.Logを組み込んでおくということは現実的ではないと考えています。

現在お客様のほうで運用している環境についてはプリザンターの画面からデータを投入するというより、
他システムからデータをAPIで登録／更新／削除することが多いため、
SysLogsへの出力が必要と考えております。
